from __future__ import annotations

from .utils import (
    COLORS,
    DIVERGING_COLORSCALE,
    PLOT_COLORWAY,
    PLOT_STYLE,
    SEQUENTIAL_COLORSCALE,
    _PLOTLY_TEMPLATE,
    _auto_show,
    _compute_bipartite_layout,
    _ensure_dataframe,
    _map_ratio_to_color,
    _maybe_save,
    _resolve_event_positions,
    apply_matplotlib_style,
    _require_matplotlib,
    _require_networkx,
    _require_plotly,
    _require_seaborn,
    go,
    make_subplots,
    choose_explain_indices,
)
from .plots import (
    animate_bipartite_graph,
    animate_stick_figure,
    build_bipartite_graph,
    happen_rate,
    plot_adjacency_heatmap,
    plot_bipartite_graph,
    plot_dataset_quadrants,
    plot_force_directed_graph,
    plot_degree_histograms,
    plot_event_count_over_time,
    plot_explain_timeline,
    plot_ground_truth_subgraph,
    plot_happen_rate_matrix,
    plot_inter_event_time_hist,
    plot_label_balance,
    plot_nicolaus_motif,
    plot_triadic_closure_subgraph,
    summarize_explain_instances,
)
from .metrics import (
    MetricCurveSpec,
    default_curve_specs,
    collect_curve_columns,
    levels_to_axis,
    prepare_metrics_plotting,
    plot_explainer_metric_summary,
    plot_metric_curves,
    plot_explainer_runtime,
    plot_prediction_match_rate,
    read_tabs_plot,
    summarize_curve_results,
)
from .exports import visualize_folder, visualize_to_files
from .workflows import visualize_dataset

__all__ = [
    # Utils
    "COLORS",
    "DIVERGING_COLORSCALE",
    "PLOT_COLORWAY",
    "PLOT_STYLE",
    "SEQUENTIAL_COLORSCALE",
    "_PLOTLY_TEMPLATE",
    "_auto_show",
    "_compute_bipartite_layout",
    "_ensure_dataframe",
    "_map_ratio_to_color",
    "_maybe_save",
    "_resolve_event_positions",
    "_require_plotly",
    "_require_networkx",
    "_require_matplotlib",
    "_require_seaborn",
    "apply_matplotlib_style",
    "choose_explain_indices",
    "go",
    "make_subplots",
    # Dataset plots
    "plot_event_count_over_time",
    "plot_inter_event_time_hist",
    "plot_degree_histograms",
    "plot_dataset_quadrants",
    "plot_adjacency_heatmap",
    "plot_label_balance",
    "plot_happen_rate_matrix",
    "plot_bipartite_graph",
    "plot_force_directed_graph",
    "plot_ground_truth_subgraph",
    "plot_triadic_closure_subgraph",
    "plot_nicolaus_motif",
    "animate_bipartite_graph",
    "animate_stick_figure",
    "plot_explain_timeline",
    "summarize_explain_instances",
    "build_bipartite_graph",
    "happen_rate",
    # Metrics
    "MetricCurveSpec",
    "default_curve_specs",
    "collect_curve_columns",
    "levels_to_axis",
    "prepare_metrics_plotting",
    "plot_metric_curves",
    "plot_explainer_metric_summary",
    "plot_explainer_runtime",
    "plot_prediction_match_rate",
    "summarize_curve_results",
    "read_tabs_plot",
    # Export helpers
    "visualize_folder",
    "visualize_to_files",
    "visualize_dataset",
]
